### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by BetterYan** [nfmcclure/tensorflow_cookbook#110]
Second logistic layer ( >>>7 hidden inputs {<- This number }<<< to 5 hidden nodes)
A2 = init_variable(shape=[14,5])
b2 = init_variable(shape=[5])
logistic_layer2 = logistic(logistic_layer1, A2, b2)

Path:
tensorflow_cookbook/06_Neural_Networks/07_Improving_Linear_Regression/07_improving_linear_regression.ipynb

**Comment by nfmcclure** [comment]
Hi @BetterYan ,

Thanks for bringing this to my attention (and sorry about the late reply). This is definitely a typo.  Since it isn't a big bug, I'm going to defer this to when I get around to chapter 6.  I'm starting to go through the code and update it for a version 2 and the current TF versions.  You should see the typo fixed in the upcoming months.  Thanks!

**Comment by nfmcclure** [comment]
This should be fixed now, thanks!
