### ISSUE TITLE
Chapter 6, Section: Improving the predictions of linear models has wrong indices.

### ISSUE THREAD

**Issue by bharathbunny** [nfmcclure/tensorflow_cookbook#128]
The dependent variable is in index 0. The factors are in indices 1:8.

After you clean up birth_data, there are empty lists that need to be removed.

**Comment by nfmcclure** [comment]
Hi @bharathbunny , thanks for bringing this up.  This is a known problem since we've changed where the data come from:
Duplicate: https://github.com/nfmcclure/tensorflow_cookbook/issues/118

I'm working on updating all the code/notebooks for a book v2 now.  I'm on chapter 5 currently.  Ch 6 is next. Expect the code fix in the next few weeks.  Thanks!

**Comment by nfmcclure** [comment]
This should be fixed now! Thanks.
