### ISSUE TITLE
questions about 01_Introduction/04_Working_with_Matrices/

### ISSUE THREAD

**Issue by idoit** [nfmcclure/tensorflow_cookbook#134]
the code is :
A = tf.truncated_normal([2,3])
print(sess.run(A))
result:
[[-0.09611617  1.50501597  0.42943364]
 [ 0.04031758 -0.66115439 -0.91324311]]
B = tf.fill([2,3], 5.0)
print(sess.run(B))
result:
[[ 5.  5.  5.]
 [ 5.  5.  5.]]
print(sess.run(A+B))
result:
[[ 3.69020724  5.68584728  4.3044405 ]
 [ 6.57195997  3.92733717  5.5748148 ]]

why is result? 

my result A+B is [[4.90388283  6.5.501597 5.42943364]
                                                      [5.04031758  4.33884561 4.08675689 ]]

**Comment by nfmcclure** [comment]
Hello, @idoit ,

Thanks for the question.  I believe the answer is because there is randomness in the `tf.truncated_normal()` function.  You'll get different answers every time you run the code.

There is future work that will fix the random-seeds for each script so that all the results will be the same.  I'm closing this issue, please feel free to re-open if you need to. Thanks.
