### ISSUE TITLE
Since the first training is done, document embedding hasn't been trained

### ISSUE THREAD

**Issue by joonable** [nfmcclure/tensorflow_cookbook#141]
Hello. I'm trying to use doc2vec algorithm in [07_Natural_Language_Processing/07_Sentiment_Analysis_With_Doc2Vec/07_sentiment_with_doc2vec.py.](https://github.com/nfmcclure/tensorflow_cookbook/tree/master/07_Natural_Language_Processing/07_Sentiment_Analysis_With_Doc2Vec)

I understood that first of the training is to **train word and doc embedding** and second one is for **text classification**, sentiment analysis. Because I needed **distributed representations of words and docs**, not a classifier, so just did first training.

After the training, I evaluated the vectors in word and document embedding using tf.saver, then found out doc embedding didn't change, but word embedding did. Doc embedding just stayed as initial value.

Did I  understand the code and doc2vec algorithm not properly or is there any kind of bug in the code? Thank you for your answer in advanced.

**Comment by nfmcclure** [comment]
Hi @joonable ,
Thanks for asking.

I just checked this out briefly.  I think I'll need more information as I cannot replicate the problem.  For example, if I run the code through the variable initialization and create a feed-dictionary, then I run the following commands:
```
In[39]: sess.run(doc_embed, feed_dict=feed_dict)
Out[39]: 
array([[[ 0.36113167, -0.42523894,  0.08636531, ...,  0.9411001 ,
         -0.8095024 , -0.38859203]],

       [[ 0.36113167, -0.42523894,  0.08636531, ...,  0.9411001 ,
         -0.8095024 , -0.38859203]],

       [[ 0.36113167, -0.42523894,  0.08636531, ...,  0.9411001 ,
         -0.8095024 , -0.38859203]],

       ...,

       [[ 0.7726636 , -0.4221473 , -0.28463227, ..., -0.00291947,
          0.49912193, -0.26189896]],

       [[ 0.7726636 , -0.4221473 , -0.28463227, ..., -0.00291947,
          0.49912193, -0.26189896]],

       [[ 0.7726636 , -0.4221473 , -0.28463227, ..., -0.00291947,
          0.49912193, -0.26189896]]], dtype=float32)
In[40]: sess.run(train_step, feed_dict=feed_dict)
In[41]: sess.run(doc_embed, feed_dict=feed_dict)
Out[41]: 
array([[[ 0.3611314 , -0.42523894,  0.08636572, ...,  0.94110006,
         -0.8095023 , -0.38859165]],

       [[ 0.3611314 , -0.42523894,  0.08636572, ...,  0.94110006,
         -0.8095023 , -0.38859165]],

       [[ 0.3611314 , -0.42523894,  0.08636572, ...,  0.94110006,
         -0.8095023 , -0.38859165]],

       ...,

       [[ 0.7726636 , -0.42214715, -0.2846323 , ..., -0.00291951,
          0.49912196, -0.26189905]],

       [[ 0.7726636 , -0.42214715, -0.2846323 , ..., -0.00291951,
          0.49912196, -0.26189905]],

       [[ 0.7726636 , -0.42214715, -0.2846323 , ..., -0.00291951,
          0.49912196, -0.26189905]]], dtype=float32)

```

This shows me that the variable `doc_embed` is changing due to the training.  Are you seeing something different?  If so, make sure you have the most up-to-date code and also let me know your python and TensorFlow versions.

I'll continue to troubleshoot with you if you see something different. I think the next step would be to fix a random seed for TensorFlow and Numpy and see what we can do, assuming we have the same versions for everything.  For reference, I'm running Python 3.6 and TensorFlow v1.10.1.

Thanks.
