### ISSUE TITLE
Arabic display issue in following your tutorial about machine translation

### ISSUE THREAD

**Issue by memoday** [nfmcclure/tensorflow_cookbook#16]
Hi Nick,

First, thanks for the great book. It's well-written and I like the way you present things. 

I have followed "Creating Sequence-to-Sequence Models" and I managed to make it work. It worked for English German, but when I used the same with English Arabic and basically got the same data from "http://www.manythings.org/anki/ara-eng.zip", the Arabic text for the examples is not displayed correctly. 

Here is what I am getting:

`English: the quick brown fox jumped over the lazy dog
arabic: ['ظ‡ظ„', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†', 'ظ…ظ†']`

What should I do to get this displayed correctly?

My other question:

once the model is trained and ready to use, how can I pass a sentence for translation? I would like to use some other sentences. 

Thanks in advance for your support.

Kind regards

**Comment by nfmcclure** [comment]
Hi @memoday ,

Thanks so much for your interest, and I'm glad you got the english-german example working. Das ist sehr toll!

I'm not sure about the arabic, but my understanding is that the model might have an issue translating a left-to-right language into a right-to-left language.

But I suspect the real issue is (1) the model can get stuck repeating the same word over and over. (it's not a complicated model).  Or (2) there might be some sort of unicode issue here.

I will investigate the second issue soon and get back to you.  But you might try increasing the depth and size of the bidirectional RNN (and possibly train for longer) to tackle the issue.  The RNN size and training length was purposely set to be smaller for illustrative purposes.

As for feeding in sentences to the model, ideally the code should be updated to (a) save the model and dictionaries, and then (b) another script should be created that can load the model/variables and evaluate a sentence.  This is a far greater effort, but you are correct, it should be done.  I will investigate the error first.  I don't have a timeline on creating an evaluation script yet, but expect something in the next few months.

**Comment by memoday** [comment]
Vielen Dank, Nick :-)

I managed to fix the encoding issue by adding 'encoding='utf8' under the 'write to file'. At least, I can see now Arabic text displayed in Jupyter Notebook. Here is the modified part.

`# Write to file
    with open(os.path.join(data_dir, data_file), 'w', encoding='utf-8') as out_conn:
        for sentence in eng_ara_data:
            out_conn.write(sentence + '\n')
else:
    eng_ara_data = []
    with open(os.path.join(data_dir, data_file), 'r', encoding='utf-8') as in_conn:
        for row in in_conn:
            eng_ara_data.append(row[:-1])`

I do hope though you can finish this great project and create something to handle sentences feeding and saving the models. This will make it complete.

Thanks again Nick for the great book. 

Kind regards,
Mohamed Zeid

**Comment by nfmcclure** [comment]
I'm glad the encoding was the primary issue.  I'll probably add the encoding in a pull request this weekend. I'm going to close this issue, as I won't get around to creating saving/evaluating for a few weeks.  I'll open another issue with a tag that expands on that for other models as well.  Thanks for the interest again,

-Nick
