### ISSUE TITLE
In 07_Natural_Language_Processing / 02_Working_with_Bag_of_Words / 02_bag_of_words.py 

### ISSUE THREAD

**Issue by yingwei13mei** [nfmcclure/tensorflow_cookbook#19]
From Line 29 to Line 34 these codes block show as follows:
"
if os.path.isfile(save_file_name): 
     text_data = [] 
     with open(save_file_name, 'r') as temp_output_file: 
         reader = csv.reader(temp_output_file) 
         for row in reader: 
             text_data.append(row) 
"
There lack a little small code when the 'temp_spam_data.csv' have been exists in local. 
There needs to split the "row" data with ',' to give to text_data. Otherwise, there will be some error message like:
"---> 53 texts = [x[1] for x in text_data]
     54 target = [x[0] for x in text_data]
IndexError: list index out of range
"

**Comment by nfmcclure** [comment]
Thanks, I'll check this out/merge a pull request soon.

**Comment by nfmcclure** [comment]
Hi @yingwei13mei ,  I've made a few updates to the code in attempts to get it working with TensorFlow v1.0.1 .   Since I've done that, I can't seem to replicate the error.  I went through and added a jupyter notebook for this example as well.  Let me know if the error still persists for you and if so, let me know your OS, python version, and TF version as well.

**Comment by TE-0000141056** [comment]
"---> 53 texts = [x[1] for x in text_data]
54 target = [x[0] for x in text_data]
IndexError: list index out of range

still exists. 
I ran this by using the latest code in jupter notebook .
could you help to check it again?
