### ISSUE TITLE
AttributeError: 'module' object has no attribute 'rnn_cell' in 09_Recurrent_Neural_Networks/03_Implementing_LSTM/03_implementing_lstm.py

### ISSUE THREAD

**Issue by woto** [nfmcclure/tensorflow_cookbook#29]
Hi, sorry, i'm absoultely new in Tensorflow and may be telling nonesence.

This example
https://github.com/nfmcclure/tensorflow_cookbook/blob/master/09_Recurrent_Neural_Networks/03_Implementing_LSTM/03_implementing_lstm.py

raise with this error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-2bd8df52813f> in <module>()
    211     # Define LSTM Model
    212     lstm_model = LSTM_Model(rnn_size, batch_size, learning_rate,
--> 213                             training_seq_len, vocab_size)
    214     scope.reuse_variables()
    215     test_lstm_model = LSTM_Model(rnn_size, batch_size, learning_rate,

<ipython-input-1-2bd8df52813f> in __init__(self, rnn_size, batch_size, learning_rate, training_seq_len, vocab_size, infer_sample)
    134             self.training_seq_len = training_seq_len
    135 
--> 136         self.lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(rnn_size)
    137         self.initial_state = self.lstm_cell.zero_state(self.batch_size, tf.float32)
    138 

AttributeError: 'module' object has no attribute 'rnn_cell'
```

```
>>> import pkg_resources
>>> pkg_resources.get_distribution("tensorflow").version
'1.0.0'
```

```
import platform
print(platform.python_version())
2.7.6
```

i'm using this Docker image

```
tensorflow/tensorflow   latest              ea40dcc45724        2 weeks ago         1.029 GB
```

thanks

**Comment by nfmcclure** [comment]
Thanks for this!  This code was indeed originally written on TensorFlow version 0.12.  I have migrated it automatically with TensorFlow's automatic upgrade script.  Theoretically that should have taken care of the 1.0.0 upgrade.  Realistically, it was far far from that.

Today, however, I managed to fix this script, so that it runs in version 1.0.1.  Please note that version number: **1.0.1**.

I recommend that you upgrade TensorFlow from 1.0.0 to 1.0.1, and repull/reclone this script.  It should be working.  Let me know if it doesn't.

Note, however, I have not upgraded the rest of the RNN chapter code in the repository because I haven't had the time yet.  I should be doing this over the next week or two.

Thanks again, and please let me know what other issues you have.
