### ISSUE TITLE
403 Forbidden when trying to access Low Birthweight Data

### ISSUE THREAD

**Issue by mclarknc** [nfmcclure/tensorflow_cookbook#74]
Clicking on the link "Low Birthweight Data" in the 07_Working_with_Data_Sources directory gets: 

You don't have permission to access /statdata/statdata/data/lowbwt.txt on this server.

**Comment by dthboyd** [comment]
Please provide working link, thanks

**Comment by TheQuant** [comment]
Agreed.  Can't access this data set using requests module either.

**Comment by nfmcclure** [comment]
It appears that UMASS has closed sourced that option for an otherwise common and open dataset.  I did some looking around and found a copy here:
http://springer.bme.gatech.edu/Ch17.Logistic/Logisticdat/birthweight.dat

I can't seem to find the license on that data link, but it should work.  In the near future, I'll upload the relatively small dataset into Github itself and reference it there.

**Comment by TheQuant** [comment]
Thanks!  That worked!

**Comment by nfmcclure** [comment]
To prevent further academic links from closing and placing un-needed stress on academia for hosting this, I moved a copy of the small birthweight dataset into a local place on this github repo here:
https://github.com/nfmcclure/tensorflow_cookbook/tree/master/01_Introduction/07_Working_with_Data_Sources/birthweight_data
I made the necessary link and code changed to the recipes/sections that use this data to reference the github location.  Please reopen if there is a problem with any of them. Thanks!
