### ISSUE TITLE
why 'embedding_size' should be equal to 'rnn_size' in chapter9 03 implementing lstm

### ISSUE THREAD

**Issue by vpegasus** [nfmcclure/tensorflow_cookbook#89]
```rnn_size = 128 # RNN Model size, has to equal embedding size```

I don't know why there has to be equal between these two hyper-params? could you be kind to explain it for us, thanks.

**Comment by nfmcclure** [comment]
Hi @vpegasus , Thanks for bringing this up.  The reason was not anything to do with the algorithm or mathematically, it was a pure programming choice.  But I realize that may be confusing to the reader, so I changed the files to have both the Embedding size and the RNN size be able to be different now.  Please repull and check to see if it makes more sense.  And please reopen if you have any more questions. I haven't fully run the file to check because it takes so long to run, so I just made sure that one epoch ran.  Of course there is no guarantee on convergence or a better solution yet.  I'll run this overnight soon and check.
